version: '3'

services:
  mongo:
      image: mongo
      container_name: mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - ~/Desktop/code/node-mongo-rest-api/data:/data/db
      networks:
        - mongo-network

  mongo-express:
    image: mongo-express:0.54
    container_name: mongoExpress
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rootName
      ME_CONFIG_BASICAUTH_PASSWORD: rootPass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootName
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootPass
    links:
        - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge